#!/bin/bash
cmd=""
for file in "$@" ; do
    if [[ ${file:0:1} != "/" ]]; then file="$PWD/$file"; fi 
    cmd="$cmd (find-file \"$file\")";      
done
if [[ -z "$cmd" ]]; then
    cmd="(new-frame)"
fi

gnuclient -batch -eval "$cmd"  > /dev/null 2> /dev/null
if (( $? )); then
    sxemacs  "$*" & 
fi
